// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-9yzNtrKg0RNw7eoYQblqdceOQGb3aQ0',
    appId: '1:118700844648:web:11a18fdfd959b1225a3ddd',
    messagingSenderId: '118700844648',
    projectId: 'crafto-bed1f',
    authDomain: 'crafto-bed1f.firebaseapp.com',
    storageBucket: 'crafto-bed1f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5soHFQRi3noJiluVQnTdAMSFH9XFCYFE',
    appId: '1:118700844648:android:09cb505937619f0f5a3ddd',
    messagingSenderId: '118700844648',
    projectId: 'crafto-bed1f',
    storageBucket: 'crafto-bed1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHwhUvVStua4E2EHQEtEcFqA9FxiS3wfA',
    appId: '1:118700844648:ios:cb7ea88f9dec74785a3ddd',
    messagingSenderId: '118700844648',
    projectId: 'crafto-bed1f',
    storageBucket: 'crafto-bed1f.firebasestorage.app',
    iosBundleId: 'com.example.crafto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHwhUvVStua4E2EHQEtEcFqA9FxiS3wfA',
    appId: '1:118700844648:ios:cb7ea88f9dec74785a3ddd',
    messagingSenderId: '118700844648',
    projectId: 'crafto-bed1f',
    storageBucket: 'crafto-bed1f.firebasestorage.app',
    iosBundleId: 'com.example.crafto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-9yzNtrKg0RNw7eoYQblqdceOQGb3aQ0',
    appId: '1:118700844648:web:2c06c3c4359026165a3ddd',
    messagingSenderId: '118700844648',
    projectId: 'crafto-bed1f',
    authDomain: 'crafto-bed1f.firebaseapp.com',
    storageBucket: 'crafto-bed1f.firebasestorage.app',
  );
}
